name: animal_app
description: "A new Flutter project."
publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_native_splash:
  flutter_screenutil: ^5.9.3
  flutter_svg: ^2.2.0


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:


  uses-material-design: true

  assets:
    - assets/images/splash/
    - assets/images/

  fonts:
    - family: Otama.ep
      fonts:
        - asset: assets/fonts/Otama-ep.otf
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
