name: animal_app
description: "A new Flutter project."
publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_native_splash:
  flutter_screenutil: ^5.9.3
  flutter_svg: ^2.2.0
  image_picker: ^1.2.1
  dotted_border: ^3.1.0
  dio: ^5.9.0
  retrofit: ^4.9.1
  json_serializable:
  get_it: ^9.2.0
  freezed:
  freezed_annotation: ^3.1.0
  json_annotation: ^4.9.0
  retrofit_generator: ^10.2.0
  pretty_dio_logger: ^1.4.0
  flutter_bloc: ^9.1.1
  build_runner: ^2.10.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:


  uses-material-design: true

  assets:
    - assets/images/splash/
    - assets/images/

  fonts:
    - family: Otama.ep
      fonts:
        - asset: assets/fonts/Otama-ep.otf
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
